name: Build GDPaho addon libraries

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Clone submodules

      - name: Set up dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev cmake scons

      - name: Set up dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install openssl
          choco install cmake
          choco install scons

      - name: Build Paho C library
        run: |
          git clone https://github.com/eclipse/paho.mqtt.c.git
          cd paho.mqtt.c
          mkdir build
          cd build
          cmake .. -DPAHO_BUILD_SHARED=FALSE -DPAHO_BUILD_STATIC=TRUE -DPAHO_HIGH_PERFORMANCE=TRUE -DPAHO_WITH_SSL=TRUE -DPAHO_ENABLE_TESTING=FALSE -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build . --target install --config "MinSizeRel"

      - name: Build Paho C++ library
        run: |
          git clone https://github.com/eclipse/paho.mqtt.cpp.git
          cd paho.mqtt.cpp
          mkdir build
          cd build
          cmake .. -DPAHO_BUILD_SHARED=FALSE -DPAHO_BUILD_STATIC=TRUE -DPAHO_WITH_SSL=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build . --target install --config "MinSizeRel"

      - name: Build the Godot library
        run: |
          cmake -DBUILD_GODOT_CPP=True -DCMAKE_BUILD_TYPE=Release . -B build
          cmake --build build

      - name: Zip export
        run: |
          zip -r ${{ matrix.os }}.zip build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.zip
          path: ${{ matrix.os }}.zip

      - name: Attach binaries to release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ${{ matrix.os }}.zip
